[theme]
base                     = "dark"
primaryColor             = "#494fdf"
backgroundColor          = "#0a0a0a"
secondaryBackgroundColor = "#16181a"
textColor                = "#ffffff"

[server]
headless             = true
port                 = 8501
enableCORS           = false
enableXsrfProtection = false
address              = "0.0.0.0"
